name: Node.js CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16.13
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm ci --no-audit
    - run: npm run lint --if-present
    - run: npm test
      env:
        CI: true
        DB_TEST_USER: postgres
        DB_TEST_PASSWORD: postgres
        DB_TEST_HOST: postgres
        DB_TEST_PORT: 5432
        DB_TEST_NAME: postgres
