name: Node.js CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      postgres:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        env:
          POSTGRES_PORT: ${{env.DB_TEST_PORT}}
          POSTGRES_HOST: ${{env.DB_TEST_HOST}}
          POSTGRES_PASSWORD: ${{env.DB_TEST_PASSWORD}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - run: npm ci --no-audit
    - run: npm run lint --if-present
    - run: npm test
    - run: npm run build --if-present
      env:
        CI: true
        DB_TEST_USER: ${{env.DB_TEST_USER}}
        DB_TEST_PASSWORD: ${{env.DB_TEST_PASSWORD}}
        DB_TEST_HOST: ${{env.DB_TEST_HOST}}
        DB_TEST_PORT: ${{env.DB_TEST_PORT}}
        DB_TEST_NAME: ${{env.DB_TEST_NAME}}
